### ISSUE TITLE
Game crashes when i exit backpack's inventory with items in it.

### ISSUE THREAD

**Issue by itkutya** [deletey/CompactStorage#170]
Error code:
```
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 2024-05-20 15:10:09
Description: keyPressed event handler

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_7225$class_7874.method_57093(com.mojang.serialization.DynamicOps)" because "$$0" is null
	at net.minecraft.class_1799.method_57376(class_1799.java:388)
	at net.minecraft.class_1799.method_57375(class_1799.java:402)
	at com.witchica.compactstorage.common.util.CompactStorageUtil.writeItemsToTag(CompactStorageUtil.java:150)
	at com.witchica.compactstorage.common.util.CompactStorageUtil.writeItemsToTag(CompactStorageUtil.java:141)
	at com.witchica.compactstorage.common.inventory.BackpackInventory.toTag(BackpackInventory.java:181)
	at com.witchica.compactstorage.common.inventory.BackpackInventory.method_5432(BackpackInventory.java:204)
	at com.witchica.compactstorage.common.screen.CompactChestScreenHandler.method_7595(CompactChestScreenHandler.java:70)
	at net.minecraft.class_465.method_25432(class_465.java:608)
	at net.minecraft.class_310.method_1507(class_310.java:1144)
	at net.minecraft.class_746.method_3137(class_746.java:348)
	at net.minecraft.class_746.method_7346(class_746.java:342)
	at net.minecraft.class_465.method_25419(class_465.java:638)
	at net.minecraft.class_465.method_25404(class_465.java:570)
	at net.minecraft.class_309.method_1454(class_309.java:418)
	at net.minecraft.class_437.method_25412(class_437.java:467)
	at net.minecraft.class_309.method_1466(class_309.java:414)
	at net.minecraft.class_309.method_22678(class_309.java:503)
	at net.minecraft.class_1255.execute(class_1255.java:108)
	at net.minecraft.class_309.method_22676(class_309.java:503)
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:200)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:218)
	at net.minecraft.class_1041.method_15998(class_1041.java:287)
	at net.minecraft.class_310.method_1523(class_310.java:1342)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_1799.method_57376(class_1799.java:388)
	at net.minecraft.class_1799.method_57375(class_1799.java:402)
	at com.witchica.compactstorage.common.util.CompactStorageUtil.writeItemsToTag(CompactStorageUtil.java:150)
	at com.witchica.compactstorage.common.util.CompactStorageUtil.writeItemsToTag(CompactStorageUtil.java:141)
	at com.witchica.compactstorage.common.inventory.BackpackInventory.toTag(BackpackInventory.java:181)
	at com.witchica.compactstorage.common.inventory.BackpackInventory.method_5432(BackpackInventory.java:204)
	at com.witchica.compactstorage.common.screen.CompactChestScreenHandler.method_7595(CompactChestScreenHandler.java:70)
	at net.minecraft.class_465.method_25432(class_465.java:608)
	at net.minecraft.class_310.method_1507(class_310.java:1144)
	at net.minecraft.class_746.method_3137(class_746.java:348)
	at net.minecraft.class_746.method_7346(class_746.java:342)
	at net.minecraft.class_465.method_25419(class_465.java:638)
	at net.minecraft.class_465.method_25404(class_465.java:570)
	at net.minecraft.class_309.method_1454(class_309.java:418)
	at net.minecraft.class_437.method_25412(class_437.java:467)
	at net.minecraft.class_309.method_1466(class_309.java:414)
	at net.minecraft.class_309.method_22678(class_309.java:503)
	at net.minecraft.class_1255.execute(class_1255.java:108)
	at net.minecraft.class_309.method_22676(class_309.java:503)
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:200)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:218)

-- Affected screen --
Details:
	Screen name: com.witchica.compactstorage.common.client.screen.CompactChestScreen
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:467)
	at net.minecraft.class_309.method_1466(class_309.java:414)
	at net.minecraft.class_309.method_22678(class_309.java:503)
	at net.minecraft.class_1255.execute(class_1255.java:108)
	at net.minecraft.class_309.method_22676(class_309.java:503)
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:200)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:218)
	at net.minecraft.class_1041.method_15998(class_1041.java:287)
	at net.minecraft.class_310.method_1523(class_310.java:1342)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Uptime --
Details:
	JVM uptime: 109.882s
	Wall uptime: 77.249s
	High-res time: 67.866s
	Client ticks: 615 ticks / 30.750s
Stacktrace:
	at net.minecraft.class_310.method_1587(class_310.java:2548)
	at net.minecraft.class_310.method_54580(class_310.java:983)
	at net.minecraft.class_310.method_1514(class_310.java:908)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['itkutya'/118, l='ClientLevel', x=-89.50, y=66.00, z=380.50]]
	Chunk stats: 1024, 409
	Level dimension: minecraft:overworld
	Level spawn location: World: (-80,65,384), Section: (at 0,1,0 in -5,4,24; chunk contains blocks -80,-64,384 to -65,319,399), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Level time: 1406 game time, 1406 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
	Tracked entity count: 114

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, caffeineconfig, compact_storage, continuity, entityculling, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-models-v0, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, immediatelyfast, indium, iris, lithium, modmenu, mr_dungeons_andtaverns, sodium, sodium-extra, sound_physics_remastered, terralith, voicechat, xaerominimap, xaeroworldmap, continuity:default, continuity:glass_pane_culling_fix

-- System Details --
Details:
	Minecraft Version: 1.20.6
	Minecraft Version ID: 1.20.6
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 2106853088 bytes (2009 MiB) / 3154116608 bytes (3008 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i3-4170 CPU @ 3.70GHz
	Identifier: Intel64 Family 6 Model 60 Stepping 3
	Microarchitecture: Haswell (Client)
	Frequency (GHz): 3.70
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: NVIDIA GeForce GTX 1050 Ti
	Graphics card #0 vendor: NVIDIA
	Graphics card #0 VRAM (MB): 4096.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 31.0.15.5244
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 1.33
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 1.33
	Memory slot #1 type: DDR3
	Memory slot #2 capacity (MB): 4096.00
	Memory slot #2 clockSpeed (GHz): 1.33
	Memory slot #2 type: DDR3
	Memory slot #3 capacity (MB): 4096.00
	Memory slot #3 clockSpeed (GHz): 1.33
	Memory slot #3 type: DDR3
	Virtual memory max (MB): 18755.38
	Virtual memory used (MB): 11532.26
	Swap memory total (MB): 2432.00
	Swap memory used (MB): 66.53
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		architectury: Architectury 12.0.1
		compact_storage: CompactStorage 7.0.71
		continuity: Continuity 3.0.0-beta.5+1.20.5
		entityculling: EntityCulling 1.6.4
		fabric-api: Fabric API 0.98.0+1.20.6
			fabric-api-base: Fabric API Base 0.4.40+80f8cf51b0
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.59+e9d2a72bb0
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.25+be5d88beb0
			fabric-block-api-v1: Fabric Block API (v1) 1.0.20+6dfe4c9bb0
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.8+80f8cf51b0
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.50+80f8cf51b0
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.12+7f945d5bb0
			fabric-command-api-v1: Fabric Command API (v1) 1.2.45+f71b366fb0
			fabric-command-api-v2: Fabric Command API (v2) 2.2.24+80f8cf51b0
			fabric-commands-v0: Fabric Commands (v0) 0.2.62+df3654b3b0
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.5+b82b2392b0
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.4+7f945d5bb0
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.1.0+70fd1b46b0
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.27+80f8cf51b0
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.16+2a2c66b6b0
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 19.1.0+ad474493b0
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.68+94793913b0
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.8+e9d2a72bb0
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.6+c5fc38b3b0
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.50+80f8cf51b0
			fabric-item-api-v1: Fabric Item API (v1) 8.2.0+5bcea88ab0
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.39+aae0949ab0
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.45+80f8cf51b0
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.43+df3654b3b0
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.4+c5fc38b3b0
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.5+97f703dab0
			fabric-message-api-v1: Fabric Message API (v1) 6.0.10+109a837cb0
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.12+80f8cf51b0
			fabric-models-v0: Fabric Models (v0) 0.4.11+9386d8a7b0
			fabric-networking-api-v1: Fabric Networking API (v1) 4.0.8+0dca0349b0
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.1.4+c5fc38b3b0
			fabric-particles-v1: Fabric Particles (v1) 4.0.0+c5fc38b3b0
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.3+c5fc38b3b0
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.0.16+ad474493b0
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.12+97f703dab0
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.12+80f8cf51b0
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.61+df3654b3b0
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.46+73761d2eb0
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.3+2c869dedb0
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.64+df3654b3b0
			fabric-rendering-v1: Fabric Rendering (v1) 4.2.4+b21c00cbb0
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.1.0+83154f1bb0
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.1.0+c0e5481fb0
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.21+7b70ea8ab0
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.73+8c7b71c2b0
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.21+c5fc38b3b0
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.6+c5fc38b3b0
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.0.10+74e2f560b0
		fabricloader: Fabric Loader 0.15.11
			mixinextras: MixinExtras 0.3.5
		ferritecore: FerriteCore 6.1.1
		geophilic: Geophilic v2.3.0
		immediatelyfast: ImmediatelyFast 1.2.15+1.20.6
			net_lenni0451_reflect: Reflect 1.3.3
		indium: Indium 1.0.30+mc1.20.4
		iris: Iris 1.7.0+mc1.20.6
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		java: OpenJDK 64-Bit Server VM 21
		lithium: Lithium 0.12.3
		minecraft: Minecraft 1.20.6
		modmenu: Mod Menu 10.0.0-beta.1
		mr_dungeons_andtaverns: Dungeons and Taverns 3.2
		sodium: Sodium 0.5.8+mc1.20.6
		sodium-extra: Sodium Extra 0.5.5+mc1.20.6-build.118
			caffeineconfig: CaffeineConfig 1.3.0+1.17
		sound_physics_remastered: Sound Physics Remastered 1.20.6-1.3.1
		terralith: Terralith 2.5.1
		voicechat: Simple Voice Chat 1.20.6-2.5.14
		xaerominimap: Xaero's Minimap 24.1.4
		xaeroworldmap: Xaero's World Map 1.38.6
	Loaded Shaderpack: BSL_v8.2.09p1.zip
		Profile: Custom (+9 options changed by user)
	Launched Version: fabric-loader-0.15.11-1.20.6
	Launcher name: minecraft-launcher
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2 GL version 3.2.0 NVIDIA 552.44, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Integrated Server (map_client.txt)
	Graphics mode: fast
	Render Distance: 10/10 chunks
	Resource Packs: vanilla, fabric, caffeineconfig, compact_storage, continuity, entityculling, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-models-v0, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, immediatelyfast, indium, iris, lithium, modmenu, mr_dungeons_andtaverns (incompatible), sodium, sodium-extra, sound_physics_remastered, terralith, voicechat, xaerominimap (incompatible), xaeroworldmap (incompatible), continuity:default, continuity:glass_pane_culling_fix
	Current Language: en_us
	Locale: en_GB
	CPU: 4x Intel(R) Core(TM) i3-4170 CPU @ 3.70GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['itkutya'/118, l='ServerLevel[New World]', x=-89.50, y=66.00, z=380.50]]
	Active Data Packs: fabric, compact_storage, fabric-convention-tags-v2, geophilic, mr_dungeons_andtaverns, terralith, vanilla, bundle, trade_rebalance, update_1_21
	Available Data Packs: bundle, compact_storage, fabric, fabric-convention-tags-v2, geophilic, mr_dungeons_andtaverns, terralith, trade_rebalance, update_1_21, vanilla
	Enabled Feature Flags: minecraft:update_1_21, minecraft:bundle, minecraft:vanilla, minecraft:trade_rebalance
	World Generation: Experimental
	World Seed: -8342730658625391782
```

**Comment by witchica** [comment]
Fixed with 7.0.72, releases are processing on both CurseForge and Modrinth
