### ISSUE TITLE
compact_storage:textures/block/compact_chest_wh\u0131te.png

### ISSUE THREAD

**Issue by BaaLXeeN** [deletey/CompactStorage#192]
we wanned play with friends "CompactStorage" mod and one of friends gOt crash we tried everything but not helped
THE İSSUE --->"Caused by: net.minecraft.ResourceLocationException: Non [a-z0-9/._-] character in path of location: compact_storage:textures/block/compact_chest_wh\u0131te.png
	at net.minecraft.resources.ResourceLocation.m_245185_(ResourceLocation.java:236) ~[client-1.20.1-20230612.114412-srg.jar%23192!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.resources.ResourceLocation.<init>(ResourceLocation.java:38) ~[client-1.20.1-20230612.114412-srg.jar%23192!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at com.witchica.compactstorage.common.client.entity.CompactChestBlockEntityRenderer.<clinit>(CompactChestBlockEntityRenderer.java:38) ~[compact-storage-1.20.1-forge-6.0.1.70.jar%23181!/:?] "

**Comment by Poopooracoocoo** [comment]
Duplicate of #188

For a workaround see https://github.com/mekanism/Mekanism/issues/4957#issuecomment-368278006

Actual fix is straightforward and you can do it yourself and then compile it.

**Comment by witchica** [comment]
fixed by https://github.com/witchica/compact-storage/tree/7c4b9af751319cae4af09b07b4b091d897ace794 for 1.20.1
